# Generated by Django 5.1.1 on 2024-09-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('teaser', models.CharField(max_length=100)),
                ('companyName', models.CharField()),
                ('location', models.CharField()),
                ('workType', models.CharField()),
                ('role', models.CharField()),
                ('salary', models.CharField()),
                ('listingDate', models.CharField()),
                ('keyword', models.CharField()),
                ('bulletPoints', models.JSONField()),
            ],
        ),
    ]
